apiVersion: v1
kind: Service
metadata:
  labels:
    name: logging-demo-loop
    tenxcloud.com/appName: logging
    tenxcloud.com/svcName: logging-demo-loop
  name: logging-demo-loop
spec:
  ports:
  - name: logging-demo-loop-0
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: logging-demo-loop
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: logging-demo-loop
    tenxcloud.com/appName: logging
    tenxcloud.com/svcName: logging-demo-loop
  name: logging-demo-loop 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: logging-demo-loop 
  template:
    metadata:
      labels:
        name: logging-demo-loop
        tenxcloud.com/appName: logging
        tenxcloud.com/svcName: logging-demo-loop
    spec:
      automountServiceAccountToken: false
      containers:
      - image: 192.168.1.55/tenxcloud/logging-loopback 
        imagePullPolicy: Always
        name: demo-loop 
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "100m"
            memory: 256Mi

