apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 512Mi
  persistentVolumeReclaimPolicy: Delete
  rbd:
    image: pv-test
    keyring: /etc/ceph/keyring
    monitors:
    - 192.168.1.86:6789
    - 192.168.1.87:6789
    - 192.168.1.88:6789
    pool: tenx-pool
    secretRef:
      name: ceph-secret-52762fc4
    user: admin
  storageClassName: tenx-rbd0
